server:
  port: 8083

spring:
  application:
    name: ms-notifications
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_auth_db
    username: ms_auth_user
    password: ms_auth_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: cambia-esta-clave-por-una-mucho-mas-larga-y-segura-en-produccion

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html